site_name: Channel Six Labs
# nav:
#   - Home: index.md
theme:
  name: material
  palette:
    scheme: slate
  font:
    text: Roboto Mono
  logo: assets/C6L_type_wide_white.png

extra_css:
  - stylesheets/extras.css
  - stylesheets/color.css

markdown_extensions:
  - github-callouts

plugins:
  - toggle-sidebar:
      async: False
      enabled: True
      theme: material
      inline: True
